lint:
  files_exist:
    - assets/multiqc_config.yml
    - CODE_OF_CONDUCT.md
    - assets/nf-core-purging_logo_light.png
    - docs/images/nf-core-purging_logo_light.png
    - docs/images/nf-core-purging_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - conf/igenomes.config
    - conf/igenomes_ignored.config
  files_unchanged:
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
    - CODE_OF_CONDUCT.md
    - assets/nf-core-purging_logo_light.png
    - docs/images/nf-core-purging_logo_light.png
    - docs/images/nf-core-purging_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
  multiqc_config: false
  nextflow_config:
    - manifest.name
    - manifest.homePage
nf_core_version: 4.1.0
repository_type: pipeline
template:
  author: "@prototaxites"
  description: A pipeline for purging retained haplotypic duplication from a genomea
    assembly.
  force: false
  is_nfcore: false
  name: purging
  org: sanger-tol
  outdir: .
  skip_features:
    - igenomes
    - multiqc
    - fastqc
  version: 1.0.0dev
